version: "3.8"

services:
  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vetbooking
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
